FORMAT: 1A
HOST: https://linguita-api.herokuapp.com/

# Linguita

Linguita is a simple API allowing language learners to get language partners to practice with them.

## Authentication [/auth/google_oauth2/]

### Send the provider code to obtain a token of the app [GET]

+ Response 200 (application/json)

        {
            "name":"Carlos Sadhu Rojas Niquen",
            "email":"carlos.sadhu@gmail.com",
            "first_name":"Carlos Sadhu",
            "last_name":"Rojas Ã‘iquen",
            "image":"https://lh5.googleusercontent.com/-iAQhBGi5aeA/AAAAAAAAAAI/AAAAAAAAAQU/KHyFkhkdzhs/photo.jpg",
            "api_token":"3e0d63d95f932d9c3ec2716b487f427d"
        }

